FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app
COPY .mvn/ .mvn
COPY ./config ./config
COPY mvnw pom.xml ./
COPY src ./src
RUN chmod 774 ./mvnw
RUN ./mvnw install -DskipTests
CMD ["./mvnw", "spring-boot:run"]