version: '3.8'
services:
  postgres:
    container_name: spring_demo_db
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=${SPRING_DATASOURCE_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  app:
    container_name: spring_boot_app    
    build:
      dockerfile: ./DockerFile
    depends_on:
      - postgres
    dns:
      - 8.8.8.8
    ports:
      - "8080:8080"