services:
  postgres:
    container_name: spring_boot_db
    image: postgis/postgis:16-3.4
    restart: always
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=${SPRING_DATASOURCE_DB}
    ports:
      - "5434:5432"
  app:
    container_name: spring_boot_app  
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    dns:
      - 8.8.8.8
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_DB=${SPRING_DATASOURCE_DB}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - CONNECTION_TO_DATABASE_HOST_PORT=${CONNECTION_TO_DATABASE_HOST_PORT}
