version: 2.1

orbs:
  docker: circleci/docker@2.7.2
  snyk: snyk/snyk@1.5.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-jdk
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: ./mvnw clean install -DskipTests

  test:
    docker:
      - image: circleci/openjdk:17-jdk
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: ./mvnw test

  docker-build-and-push:
    docker:
      - image: circleci/openjdk:17-jdk
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Docker Login
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker/build:
          image: your_dockerhub_username/your_image_name:latest
      - docker/push:
          image: your_dockerhub_username/your_image_name:latest

  deploy:
    executor: heroku/default
    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku stack:set container -a ttanttanyj-su-devops
            heroku container:push web -a ttanttanyj-su-devops
            heroku container:release web -a ttanttanyj-su-devops

workflows:
  release_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - docker-build-and-push:
          requires:
            - build
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - docker-build-and-push
          filters:
            tags:
              only: /^v.*/
