name: Java CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    env:
      SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
      SPRING_DATASOURCE_DB: ${{ secrets.SPRING_DATASOURCE_DB }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      CONNECTION_TO_DATABASE_HOST_PORT: ${{ secrets.CONNECTION_TO_DATABASE_HOST_PORT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and run Docker Compose
        run: docker compose up -d --build

      - name: Run SpotBugs
        run: docker exec spring_boot_app ./mvnw spotbugs:check

      - name: Run Tests
        run: docker exec spring_boot_app ./mvnw test
