name: Java CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    env:
      SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
      SPRING_DATASOURCE_DB: garang-guni
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and run Docker Compose
        run: docker-compose up -f "docker-compose.yml" -d --build

      - name: Run SpotBugs
        run: mvn spotbugs:check

      - name: Run Tests
        run: mvn test
